### ISSUE TITLE
mysql2spatial is not being used when using ar-octupus

### ISSUE THREAD

**Issue by innovia** [tchandy/octopus#182]
https://github.com/dazuma/activerecord-mysql2spatial-adapter

how can i make sure this works:

 establish_connection Rails.configuration.database_configuration[Rails.env].merge('adapter' => "mysql2spatial"

i am using unicorn here's my unicorn config

before_fork do |server, worker|
 ActiveRecord::Base.connection_proxy.instance_variable_get(:@shards).each do |shard, connection_pool|
    connection_pool.disconnect!
  end
end

after_fork do |server, worker|
  GTRedis.instance.client.reconnect
  Resque.redis.client.reconnect
  Rails.cache.reconnect
end

**Comment by sobrinho** [comment]
You need to change the adapter on shards.yml like this:

``` yaml
octopus:
  replicated: true
  fully_replicated: true
  verify_connection: true
  environments:
    - production

  production:
    replica1:
      adapter: "mysql2spatial"
      database: "production"
      username: "user"
      password: "password"
      host: "replica1.server.com"
      encoding: "utf8"
      reconnect: true
```
