### ISSUE TITLE
How to use multiple queries on the same shard

### ISSUE THREAD

**Issue by alecslupu** [tchandy/octopus#196]
Hello!
In my shards.yml i have something like this: 

```
octopus:
  replicated: true
  fully_replicated: true
  environments:
    - development
    - production
    - staging 
    - test
  development:
    shards:
      shard_one:
         .... 
      shard_two:
         ....
```

In my application_controller.rb i have : 

```
    def use_slave(&block)
      raise "Cannot use slave when in a GET request" unless request.method == "GET"
      Octopus.using(select_slave, &block)
    end
     
    def select_slave
      [:shard_one, :shard_two].sample
    end
```

I have an around filter, like this in one of my controllers. 
```
  around_filter :use_slave, :only =>  [ :index ] 
```

In that action and it's view (through helpers) i am executing more queries, and my expected behavior would be to send all those queries to a specific shard. However, it seems that just one or at most 2 of the queries are using the shard, and the rest (let's say 10 Select) statements, are changed automatically on master. Or, at least my logger does not show i am using any shard. 
Is there any way i could force that behavior, meaning i force all my queries to use the desired shard?

Of course i do not want to put it at a Model level because i am expecting to use a ReadOnly database.
