### ISSUE TITLE
Migrations with octopus

### ISSUE THREAD

**Issue by maxrails** [tchandy/octopus#211]
I've got master and slave replica with Mysql. In project using rails 3.2, project is not new - so got a lot of previous migrations. 

When I add gem and try at production migrate database with a couple new migrations - somehow it start migrations from the beginning.

shards.yml:

``` yaml
octopus:
  replicated: true
  fully_replicated: true
  octopus_enviroments:
    - production
  production:
    shards:
      slave1: 
```

Using amazon rds for both master and slave. 
I removed gem and migrations passed successfully. Then try to add gem again and rake db:migrate - again it fails. Is there some workaround ? Thanks
