### ISSUE TITLE
Database results get mixed up

### ISSUE THREAD

**Issue by shobee** [tchandy/octopus#217]
Hi everybody,

we are struggeling with a strange problem, similar to this issue: https://github.com/tchandy/octopus/issues/108

After logging and focusing a lot of time we can say that if there are more than one database request coming from different unicorn workers the results from the database don't return to the correct model. More precise, within this line the record is instantiated with attributes returning from a different request:

https://github.com/rails/rails/blob/ceb33f84933639d3b61aac62e5e71fd087ab65ed/activerecord/lib/active_record/querying.rb#L38

This occurs only sometimes but easy reproducable in our environment.

We're not sure for 100% but it seems it has to do with octopus because this problem only occurs when we're using `replicated: true` for reading from a slave database. As soon as we are reading from master everything works fine. Even when we're setting the slave database as master, we really have tried all combinations to ensure there is no problem with our replication.

Here is our setup:
- unicorn 4.6.0
- rails 3.2.16
- mysql2 0.3.14
- octopus 0.8.0

database.yml:
```
production:
  host: master.foo.org
  adapter: mysql2
  database: some_db
  encoding: utf8
  pool: 25
  username: john_doe
  password: secret
```

shards.yml:
```
octopus:
  replicated: true
  environments:
    - production

  production:
    slave1: 
      host: slave.foo.org
      adapter: mysql2
      database: some_db
      encoding: utf8
      pool: 25
      username: john_doe
      password: secret
```

Thanks in advance for any hints or ideas!
