### ISSUE TITLE
Write-only master and read-only slaves not working properly.

### ISSUE THREAD

**Issue by lemavri** [tchandy/octopus#243]
After configuring our application as follows, we are still getting read queries in the master. We're running Rails 4 with Ruby 2.1.0.

```
#shards.yml
octopus:
  replicated: true
  fully_replicated: true
  environments:
    - production

  production:
    slave1:
      adapter: mysql2
      host: x.x.x.x
      database: db_anem
      username: user
      password: asdasdasd

    slave2:
      adapter: mysql2
      host: x.x.x.x
      database: db_name
      username: user
      password: asdasdasd
```
```
#database.yml
production:
  adapter: mysql2
  host: x.x.x.x
  database: db_name
  username: user
  password: asdasdasd
  reconnect: true
  wait_timeout: 2147483
```
