### ISSUE TITLE
Pending Migration Error

### ISSUE THREAD

**Issue by michaelachrisco** [tchandy/octopus#294]
I have two separate shards: 
* API shard
* Administration shard (Users/etc..)

Our shards currently look like this:
```
octopus:
  environments:
    - development
    - production
    - test
  development:
    api:
      adapter: sqlite3
      database: db/api_dev.sqlite3

    services:
      adapter: sqlite3
      database: db/services_dev.sqlite3

  production:
    api:
      adapter: sqlite3
      database: db/api.sqlite3

    services:
      adapter: sqlite3
      database: db/services.sqlite3

  test:
    api:
      adapter: sqlite3
      database: db/api_test.sqlite3

    services:
      adapter: sqlite3
      database: db/services_test.sqlite3

# default_migration_group: services
``` 

Create Driver migration: 
```Ruby
class CreateDrivers < ActiveRecord::Migration
  using(:api)

  def change
    create_table :drivers do |t|
      t.integer :driver_number
      t.string :first_name
      t.string :last_name
      t.string :driver_type

      t.timestamps
    end
  end
end
```
Doorkeeper gem Migration:
```Ruby
class CreateDoorkeeperTables < ActiveRecord::Migration
  using(:services)
  
  def change
    create_table :oauth_applications do |t|
      t.string  :name,         null: false
      t.string  :uid,          null: false
      t.string  :secret,       null: false
      t.text    :redirect_uri, null: false
      t.string  :scopes,       null: false, default: ''
      t.timestamps
    end

    add_index :oauth_applications, :uid, unique: true

    create_table :oauth_access_grants do |t|
      t.integer  :resource_owner_id, null: false
      t.integer  :application_id,    null: false
      t.string   :token,             null: false
      t.integer  :expires_in,        null: false
      t.text     :redirect_uri,      null: false
      t.datetime :created_at,        null: false
      t.datetime :revoked_at
      t.string   :scopes
    end

    add_index :oauth_access_grants, :token, unique: true

    create_table :oauth_access_tokens do |t|
      t.integer  :resource_owner_id
      t.integer  :application_id
      t.string   :token,             null: false
      t.string   :refresh_token
      t.integer  :expires_in
      t.datetime :revoked_at
      t.datetime :created_at,        null: false
      t.string   :scopes
    end

    add_index :oauth_access_tokens, :token, unique: true
    add_index :oauth_access_tokens, :resource_owner_id
    add_index :oauth_access_tokens, :refresh_token, unique: true
  end
end
```
I am recieving an error: 

```Bash
$ bundle exec rake db:drop db:create db:migrate RAILS_ENV_test
$ rspec
ActiveRecord::PendingMigrationError: 

Migrations are pending. To resolve this issue, run:

        bin/rake db:migrate RAILS_ENV=test


           check_pending! at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/activerecord-4.1.5/lib/active_record/migration.rb:389
  load_schema_if_pending! at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/activerecord-4.1.5/lib/active_record/migration.rb:395
    maintain_test_schema! at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/activerecord-4.1.5/lib/active_record/migration.rb:401
        suppress_messages at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/activerecord-4.1.5/lib/active_record/migration.rb:629
           method_missing at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/activerecord-4.1.5/lib/active_record/migration.rb:406
    maintain_test_schema! at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/activerecord-4.1.5/lib/active_record/migration.rb:401
                   (root) at /Users/michaelchrisco/dev/development/gman-services/spec/rails_helper.rb:26
                  require at org/jruby/RubyKernel.java:1065
                   (root) at /Users/michaelchrisco/dev/development/gman-services/spec/controllers/api/v1/trucking/driver_commissions_history_controller_spec.rb:1
                     load at org/jruby/RubyKernel.java:1081
                   (root) at /Users/michaelchrisco/dev/development/gman-services/spec/controllers/api/v1/trucking/driver_commissions_history_controller_spec.rb:1
                     each at org/jruby/RubyArray.java:1613
                   (root) at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1
          load_spec_files at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105
          load_spec_files at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105
                    setup at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96
                      run at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84
                      run at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69
                     load at org/jruby/RubyKernel.java:1081
                   invoke at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37
                     eval at org/jruby/RubyKernel.java:1101
                   (root) at /Users/michaelchrisco/.rvm/gems/jruby-1.7.16.1/gems/rspec-core-3.1.7/exe/rspec:4
```
Any ideas?
