### ISSUE TITLE
migration with using shard is not run as expected

### ISSUE THREAD

**Issue by lazing** [tchandy/octopus#313]
assume two shard default: master and another shard common_shard
two migrations:
first is normal rails migration, migrated in master;
second is as:

````
class CreateCommonCategories < ActiveRecord::Migration
  using :common_shard
  def change
    Octopus.using(:common_shard) do
      create_table :categories do |t|

````
which is new pending migration.

when i remove line: `Octopus.using...` , no migration happened when rake db:migrate.
which in my idea, should work.

after added the line, the migration worked as expected, but when I run rake db:rollback
the master rollback not the previous migrate

**Comment by lazing** [comment]
more information, with the success migration, failed at server startup

````
ActiveRecord::PendingMigrationError
Migrations are pending. To resolve this issue, run: bin/rake db:migrate RAILS_ENV=development
````
rails 4.2.1
ar-octopus  0.8.5

**Comment by sobrinho** [comment]
I'm not able to reproduce using the master version.

``` yaml
octopus:
  environments:
    - development

  development:
    alpha:
      adapter: sqlite3
      database: db/alpha.sqlite3
      pool: 5
      timeout: 5000

    beta:
      adapter: sqlite3
      database: db/beta.sqlite3
      pool: 5
      timeout: 5000
```

``` ruby
class CreatePages < ActiveRecord::Migration
  def change
    create_table :pages do |t|
      t.string :title

      t.timestamps
    end
  end
end
```

``` ruby
class CreateComments < ActiveRecord::Migration
  using :alpha

  def change
    create_table :comments do |t|
      t.belongs_to :page, index: true
      t.text :body

      t.timestamps
    end
  end
end
```

```
λ bin/rake db:migrate
== 20150810151349 CreateComments: migrating - Shard: alpha ====================
-- create_table(:comments)
   -> 0.0042s
== 20150810151349 CreateComments: migrated (0.0043s) - Shard: alpha ===========

== 20150810121651 CreatePages: migrating - Shard: master ======================
-- create_table(:pages)
   -> 0.0032s
== 20150810121651 CreatePages: migrated (0.0033s) - Shard: master =============
```

Can you try against master version?

**Comment by lazing** [comment]
@sobrinho the project i used is a bit complex, will check out later

**Comment by ddevaal** [comment]
I'm having the same problem. Why are my migrations not running?

** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate

And then nothing? I have tried running the migration code in a console but totally ignored using() and just picks my default database.

**Comment by sobrinho** [comment]
@ddevaal did you configured your config/shards.yml?

**Comment by ddevaal** [comment]
@sobrinho This is probably due to my limited understanding of how Rails works with multiple databases. For some reason when I run rake db:migrate it picks up the default database from database.yml which has a different schema_migrations table. I was under the impression that using, using :shard_name in the migration would also I take this into account.

**Comment by sobrinho** [comment]
@ddeval you must configure your config/shards.yml just like I showed here: https://github.com/tchandy/octopus/issues/313#issuecomment-145386877

**Comment by ddevaal** [comment]
@sobrinho I did. This is my config:

```
octopus:
  environments:
    - development
  development:
    shard1:
      host: shard1host
      adapter: sqlserver
      database: shard1database
      username: username
      password: password
      dataserver: shard1host\ACCEPTATIE
      port: 1435
      
   shard2:
      host: shard2host
      adapter: sqlserver
      database: shard2database
      username: username
      password: password
      dataserver: shard2host\ACCEPTATIE
      port: 1435
      
    shard3:
      host: shard3host
      adapter: mysql2
      database: shard3database
      encoding: utf8
      username: username
      password: password
      port: 8888
      
    shard4:
      host: shard4host
      adapter: mysql2
      database: shard4database
      encoding: utf8
      username: username
      password: password
      port: 8889
```

When I do a rake:db:migrations:status I see a lot of earlier migrations but those are from the shard1database.
