### ISSUE TITLE
Support for connection URLs in shards.yml

### ISSUE THREAD

**Issue by hosh** [tchandy/octopus#330]
I noticed that the `shards.yml` parsing doesn't support connection URLs.

Are there plans for this in the future?

**Comment by sobrinho** [comment]
It does, take a look [here](https://github.com/tchandy/octopus/blob/0c65c5b485481fbe1c0a87bf97271235de99af82/spec/config/shards.yml#L52).

Feel free to reopen if there is a problem but it's probably a misconfiguration.

**Comment by donaldpiret** [comment]
I have a feeling that it doesn't work when used as part of a shard group. Works if you use individual shard names, but as soon as you nest it under a shard group things start failing.

Here's an example config that doesn't work:

```
octopus:
  environments:
    - development
  replicated: true
  fully_replicated: false
  default_migration_group: master
  development:
    read_replicas:
      <% ENV['DB_READ_REPLICA_URLS'].to_s.split(',').each_with_index do |read_replica, i| %>
      replica<%= i %>: <%= read_replica %>
      <% end %>
```
