### ISSUE TITLE
Slowness when loading assets

### ISSUE THREAD

**Issue by chzchris** [tchandy/octopus#338]
Hi,
   I am adopting Octopus in my Rails project recently and I am experiencing a weird slowness when enabling replication. My project usually loads javascript and css from assets folder when logging in the index page. It usually runs really fast in my local development environment. But once I enabled octopus and used full replication, it ran very slow to load the resources from assets folder and there is no error message. I am using the same database in my shards.xml just for testing purpose so it is the same configuration with master database. Below are my database.yml and shards.yml:

database.yml
```
development:
  adapter: mysql2
  database: dash_dev
  username: dash_dev
  password: dev1234
  host: localhost
  port: 3306
  encoding: utf8
```

shards.yml
```
octopus:
  replicated: true
  fully_replicated: true
  environments:
    - development

  development:
    slave_01:
      adapter: mysql2
      database: dash_dev
      username: dash_dev
      password: dev1234
      host: localhost
      port: 3306
      encoding: utf8
      pool: 5
      timeout: 5000
```
Ruby version: 1.9.3
Rails: 3.1.11

Any idea or where should I start to investigate? Thanks!
