### ISSUE TITLE
Postgres Disabling Prepared Statements Breaks with Replication

### ISSUE THREAD

**Issue by ahueniken** [tchandy/octopus#339]
If your database.yml sets prepared_statements to be false (in my case we need to to use pgbouncer)

```yml
default: &default
    adapter: postgresql
    prepared_statements: false
    pool: 5
    timeout: 5000
```

You'll get the following error
```
PG::ProtocolViolation: ERROR:  bind message supplies 1 parameters, 
but prepared statement "a1" requires 0
: SELECT  "people".* FROM "people" WHERE "people"."id" = 1 LIMIT 1
````

For a simple call like `@person = Person.find(params[:id])`
In shards.yml I have `fully_replicated: true`

What's odd however is that on Heroku with pgbouncer in place, it appears to be working with prepared_statements: false, just on my local machine it breaks. 

Has anyone experiment with prepared statements and octopus?
